CREATE TABLE IF NOT EXISTS ticket_assignments (
id INT AUTO_INCREMENT PRIMARY KEY,
ticket_id INT NOT NULL,
assigned_to INT NOT NULL,
assigned_by INT NOT NULL,
assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (assigned_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;